pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker run -v $PWD/UPF:/UPF logicalhacking:isabelle2020 isabelle build -D /UPF'
            }
        }
    }
}
